"""ApprovalTask SQLAlchemy model — human-in-the-loop approval record."""

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base
from app.models.enums import ApprovalStatus, ApprovalType


class ApprovalTask(Base):
    __tablename__ = "approval_tasks"
    __table_args__ = (
        CheckConstraint("version >= 1", name="ck_approval_version_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    agent_session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("agent_sessions.id", ondelete="SET NULL"), nullable=True
    )
    turn_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    action_id: Mapped[str] = mapped_column(
        String(64), unique=True, nullable=False,
        comment="Canonical action_id from pending_action — unique, guarantees at-most-one approval per action",
    )
    tool_name: Mapped[str] = mapped_column(
        String(50), nullable=False
    )
    sanitized_action_payload: Mapped[dict] = mapped_column(
        JSONB, nullable=False,
        comment="Verified canonical_tool_input from pending_action — PII stripped, NOT client-submitted",
    )
    approval_type: Mapped[ApprovalType] = mapped_column(
        Enum(ApprovalType, name="approval_type", create_constraint=False),
        nullable=False,
    )
    status: Mapped[ApprovalStatus] = mapped_column(
        Enum(ApprovalStatus, name="approval_status", create_constraint=False),
        nullable=False, server_default="PENDING", index=True,
    )
    risk_level: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="LOW",
    )
    reason: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        comment="Why this action requires approval (generated by the system)",
    )
    requested_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False,
        comment="user_id who triggered the action",
    )
    decided_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True,
        comment="admin/operator who made the decision",
    )
    decision_reason: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        comment="Admin's reason for approve/reject",
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        server_default=func.text("now() + interval '72 hours'"),
    )
    decided_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(),
    )
